### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by Tezeug** [kamilbl/NuBot#1]
Hello.
Do not you plan to make a bot, based on something like is from @yasinkuyu?

@yasinkuyu/binance-trader

**Comment by kamilbl** [comment]
Hello. 
I want make a simple bot with a lot of strategy.

**Comment by tezeug** [comment]
I think it also can be a very simple bot.
It just places order between bid and ask when there is a set spread (e. g. 0.2 %).

**Comment by kamilbl** [comment]
What do you mind? Have you idea about strategy deph ? 
Bot will buy coins for X-price and sell coins Y-price. Diffrent between prices will be minimal spread (0.3%).

**Comment by kamilbl** [comment]
Ok I think I understand. But do we should in the first operation buy XLM and waiting when order will be done? And in the next step bot create sell order.

**Comment by tezeug** [comment]
Exactly, yes. It places a buy order, waits until it is filled (if the trade is still profitable, if not, it is immediatelly cancelled). If new buy order appears which wants to buy the coin for a higher price, the bot cancels the current order and puts a new one (if the trade is still profitable). When the order is filled, then puts a sell order in the same way (based on the same principle).

**Comment by tezeug** [comment]
Basically, you have already written the strategies so it would not be so hard and I think it could be very effective while trading a coin with a huge volume (like that XLM which has also got a good spreads) + not so depending on the market situation.
You can also edit the @yasinkuyu’s code who has already written quite similar bot but it is very outdated (does not work properly) and there are no indicators so it does not know when it would be good to stop and when not.

**Comment by kamilbl** [comment]
Ok. I think I can this do. Today I start  your strategy 👍 👍👍

**Comment by tezeug** [comment]
I’ll be waiting for the first release. Then I’ll also help you with the testing.

**Comment by tezeug** [comment]
Check this repo (fork of yasinkuyu’s) out.
https://github.com/devcryptoph/binance-trader_old
I’ve tested it and it is fully working. It just sometimes shows some errors so the code would need improvements but you could make your own fork of it, edit it and implement it into your bot + add the indicators.

**Comment by kamilbl** [comment]
Hello. 
I need to add controling errors on trading market: >>> [Link](https://github.com/binance-exchange/binance-official-api-docs/blob/master/errors.md)
I will add controls comunicate about errors.

**Comment by kamilbl** [comment]
Can you tell me about your errors ? Do you have any comunicate ?

**Comment by kamilbl** [comment]
I added comunicate about errors. If you want you can testing.
